# Generated by Django 6.0.2 on 2026-02-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=255, verbose_name='ชื่อโครงงาน (ไทย)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='ชื่อโครงงาน (อังกฤษ)')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('proposal', 'เสนอโครงร่าง'), ('approved', 'อนุมัติแล้ว'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_advisor', to=settings.AUTH_USER_MODEL, verbose_name='อาจารย์ที่ปรึกษา')),
                ('co_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_co_advisor', to=settings.AUTH_USER_MODEL, verbose_name='อาจารย์ที่ปรึกษาร่วม')),
                ('students', models.ManyToManyField(related_name='projects_as_student', to=settings.AUTH_USER_MODEL, verbose_name='นักศึกษา')),
            ],
            options={
                'verbose_name': 'โครงงาน',
                'verbose_name_plural': 'โครงงาน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('vt_p1', 'วท.ป.1 แบบประเมินกรอบของโครงงาน'), ('vt_p2', 'วท.ป.2 แบบประเมินการสอบหัวข้อโครงงาน'), ('vt_p3', 'วท.ป.3 แบบประเมินผลความก้าวหน้าของโครงงาน'), ('vt_p3_1', 'วท.ป.3-1 แบบประเมินผลความก้าวหน้าของโครงงาน'), ('vt_p4', 'วท.ป.4 แบบประเมินผลการสอบโครงงาน'), ('vt_p5', 'วท.ป.5 แบบประเมินผลการสอบโครงงาน')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, verbose_name='ความเห็น')),
                ('strengths', models.TextField(blank=True, verbose_name='จุดเด่น')),
                ('improvements', models.TextField(blank=True, verbose_name='ข้อเสนอแนะ')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='final_pro.project')),
            ],
            options={
                'verbose_name': 'แบบประเมิน',
                'verbose_name_plural': 'แบบประเมิน',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('vt_1', 'วท.1 แบบคำขอเป็นที่ปรึกษา'), ('vt_2', 'วท.2 คำขออนุมัติโครงร่างโครงงานและอาจารย์ที่ปรึกษา'), ('vt_3', 'วท.3 แบบขอสอบ - ขออนุมัติโครงงาน'), ('vt_4', 'วท.4 แบบรายงานความก้าวหน้าโครงงาน'), ('vt_5', 'วท.5 แบบขอสอบโครงงาน'), ('vt_6', 'วท.6 แบบขอเปลี่ยนอาจารย์ที่ปรึกษา'), ('vt_7', 'วท.7 แบบขอเปลี่ยนสมาชิกโครงงาน'), ('vt_9', 'วท.9 แบบทะเบียนประวัติผู้รับผิดชอบโครงงาน'), ('vt_10', 'วท.10 แบบเปลี่ยนขอบเขตโครงงาน'), ('vt_11', 'วท.11 แบบบันทึกการตรวจรูปแบบโครงงาน'), ('vt_12', 'วท.12 แบบขอเปลี่ยนหัวข้อโครงงาน'), ('vt_13', 'วท.13 ขออนุมัติเข้าเล่มโครงงาน'), ('vt_14', 'วท.14 แบบรับรองการตรวจเนื้อหาโครงงาน')], max_length=20)),
                ('request_details', models.TextField(verbose_name='รายละเอียดคำขอ')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล')),
                ('status', models.CharField(choices=[('pending', 'รอพิจารณา'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ'), ('revision', 'ต้องแก้ไข')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True, verbose_name='หมายเหตุการอนุมัติ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='final_pro.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'แบบคำขอ',
                'verbose_name_plural': 'แบบคำขอ',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='final_pro.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การส่งงาน',
                'verbose_name_plural': 'การส่งงาน',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(default='วิทยาการคอมพิวเตอร์', max_length=100)),
                ('role', models.CharField(choices=[('student', 'นักศึกษา'), ('advisor', 'อาจารย์ที่ปรึกษา'), ('committee', 'กรรมการ')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
